### ISSUE TITLE
Target platform for Android 4.1.0 is not installed.

### ISSUE THREAD

**Issue by ciddu2000** [rhomobile/rhodes#959]
Hello,

I am under linux mint 17.3, I am trying to run the example application "storemanager" with the command : `rake run:android ` , but when I run it, I got this output : 

```
rake aborted!
Target platform for Android 4.1.0 is not installed. Please, install corresponding packages in Android SDK 
Manager or correct build.yml values.
```

I have that rhodes settings :

```
rhodes-setup
We will ask you a few questions below about your dev environment.

JDK path (required) (): /usr/lib/jvm/java-8-openjdk-amd64
Invalid JDK path
JDK path (required) (): /usr/lib/jvm/java-1.8.0-openjdk-amd64/
Invalid JDK path
JDK path (required) (): /usr/lib/jvm/java-8-openjdk-amd64/jre
Invalid JDK path
JDK path (required) (): /opt/android-studio/jre
Android SDK path (blank to skip) (): /home/gaut/Android/Sdk
Android NDK path (blank to skip) (/home/gaut/Android/android-ndk-r15c): /home/gaut/Android/android-ndk-r15c
Windows Mobile 6 SDK CabWiz (blank to skip) (): 
BlackBerry JDE 4.6 (blank to skip) (): 
BlackBerry JDE 4.6 MDS (blank to skip) (): 
BlackBerry JDE 4.2 (blank to skip) (): 
BlackBerry JDE 4.2 MDS (blank to skip) (): 

If you want to build with other BlackBerry SDK versions edit: /var/lib/gems/2.3.0/gems/rhodes-6.0.11/rhobuild.yml
```

and that build.yml file :

```
---
sdkversion: 6.0.0
name: storemanager
version: 1.0
vendor: rhomobile
rho_app_id: com.rhomobile.storemanager
build: debug
applog: rholog.txt
iphone:
  configuration: Release
  sdk: latest
  BundleIdentifier: com.rhomobile.storemanager
  BundleURLScheme: storemanager
uwp:
  productid: 6782d650-5a09-0136-54b9-70761cace628
  target: ARM
android:
  version: 4.1.0
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E
wm:
  extensions:
  - webkit
win32:
  deployqt: 1
  deploymsvc: 1
extensions: []
rhobundle:
  exclude_items:
  - thumb.db
sdk: 
```
and here is the end of the output given by  the command : 
```
[INFO]	Building APK file...

THIS TOOL IS DEPRECATED. See --help for more information.

[INFO]	Align Debug APK file
[INFO]	Signing APK file
rm -rf /home/gaut/Bureau/projet_programmation/storemanager/bin/target/android/storemanager-tmp.apk
rm -rf /home/gaut/Bureau/projet_programmation/storemanager/bin/target/android/storemanager-tmp_signed.apk
[INFO]	Look for 'adb logcat' processes
rake aborted!
Target platform for Android 4.1.0 is not installed. Please, install corresponding packages in Android SDK Manager or correct build.yml values.
/var/lib/gems/2.3.0/gems/rhodes-6.0.11/platform/android/build/android_tools.rb:330:in `run_emulator'
/var/lib/gems/2.3.0/gems/rhodes-6.0.11/platform/android/build/android.rake:2752:in `block (4 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rhodes-6.0.11/Rakefile:111:in `execute'
/var/lib/gems/2.3.0/gems/rhodes-6.0.11/Rakefile:4519:in `invoke'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => run:android => run:android:emulator => run:android:emulator:run
(See full trace by running task with --trace)
 **** NOTE: You use sdk parameter in build.yml ****************************************************************
   To use latest Rhodes gem, run migrate-rhodes-app in application folder or comment sdk in build.yml.
 **************************************************************************************************************
```

What should I do to to get it working?

thanks for your answers.
